### ISSUE TITLE
Editable version intro slides

### ISSUE THREAD

**Issue by DipFlip** [ASamarkRoth/FYSC12-Labs#3]
Hej!
Does anyone have the editable version of fysc12_labguidelines.pdf?
Cheers

**Comment by donpicoro** [comment]
Those predate me... I got them from Edgar Kellerman (HEP). They are short and simple... maybe we should take the time to put them into PPT/TeX format that we can use.

**Comment by DipFlip** [comment]
Ok I think Daniel worked around it so the text is up to date :)
